title = "Tshepang logs"
base_url = "http://tshepang.github.io"
theme = "even"
generate_rss = true
build_search_index = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "categories", rss = true },
]

[markdown]
highlight_code = true

[extra]
author = "Tshepang Lekhonkhobe"
hyde_links = [
  { name = 'twitter', url = 'https://twitter.com/tshepang_dev' },
  { name = 'github', url = 'https://github.com/tshepang' },
]
even_menu = [
    {url = "$BASE_URL/tags", name = "tags"},
    {url = "$BASE_URL/about-me", name = "about"},
    {url = "$BASE_URL/categories/movies", name = "movies"},
]
even_title = "Tshepang logs"
even_google_analytics = "UA-16685250-3"
even_search = true
