title = "Tshepang logs"
base_url = "http://tshepang.net"
compile_sass = true
highlight_code = true
theme = "even"
generate_rss = true
taxonomies = [
  { name = "tags", rss = true },
]

[extra]
author = "Tshepang Lekhonkhobe"
hyde_links = [
  { name = 'twitter', url = 'https://twitter.com/tshepang_dev' },
  { name = 'github', url = 'https://github.com/tshepang' },
]
even_menu = [
    {url = "$BASE_URL/tags", name = "tags"},
    {url = "$BASE_URL/about-me", name = "about"},
]
even_title = "Tshepang logs"
