title = "Tshepang logs"
base_url = "https://tshepang.github.io"
theme = "zerm"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "categories", rss = true },
]

[markdown]
highlight_code = true

[extra]
main_menu = [
    {url = "about-me", name = "about"},
    {url = "tags", name = "tags"},
    {url = "categories/movies", name = "movies"},
]
author = "Tshepang"
theme_color = "blue"
show_author = false
show_tags = true
show_categories = true
center = true
logo_text = "Tshepang logs"
