title = "Tshepang logs"
base_url = "https://tshepang.github.io"
theme = "even"
generate_rss = true
build_search_index = true
markdown.highlight_code = true

[[taxonomies]]
  name = "tags"
  rss = true

[[taxonomies]]
  name = "categories"
  rss = true

[extra]
 even_title = "Tshepang logs"

[[extra.even_menu]]
  name = "about"
  url = "$BASE_URL/about-me"

[[extra.even_menu]]
  name = "tags"
  url = "$BASE_URL/tags"

[[extra.even_menu]]
  name = "movies"
  url = "$BASE_URL/categories/movies"
