base_url = "https://tshepang.github.io"
theme = "blow"
generate_feed = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "categories", rss = true },
]

[markdown]
highlight_code = true

[extra]
enable_search = true

[extra.navbar]
title = "Tshepang logs"

[[extra.navbar.items]]
lang = "en"

[[extra.navbar.items.links]]
url = "about-me"
name = "about"

[[extra.navbar.items.links]]
url = "tags"
name = "tags"

[[extra.navbar.items.links]]
url = "categories/movies"
name = "movies"


[extra.social]
github = "https://github.com/tshepang"
twitter = "https://twitter.com/tshepang_dev"
email = "tshepang@gmail.com"
