title = "Tshepang logs"
base_url = "http://tshepang.github.io"
theme = "after-dark"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "categories", rss = true },
]

[markdown]
highlight_code = true

[extra]
after_dark_menu = [
    {url = "$BASE_URL/tags", name = "tags"},
    {url = "$BASE_URL/about-me", name = "about"},
    {url = "$BASE_URL/categories/movies", name = "movies"},
]
