title = "Tshepang logs"
base_url = "https://tshepang.github.io"
theme = "zola.386"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", rss = true },
  { name = "categories", rss = true },
]

[markdown]
highlight_code = true

[extra]
zola386_menu = [
    { path = "", name = "home" },
    { path = "about-me", name = "about" },
    { path = "tags", name = "tags" },
    { path = "categories/movies", name = "movies" },
]
keywords = "computing, arts"
author = "Tshepang"
year = "2021"
theme_color = "#000084"
label_category = "category"
label_categories = "categories"
label_date = "date"
label_author = "author"
label_taxonomy = "taxonomy"
label_reading = "reading time"
label_read_more = "read more"
label_tag = "tag"
label_tags = "tags"
