#!/bin/bash -e

OUTPUTDIR='.output'
zola build
rm --recursive $OUTPUTDIR/*
cp --recursive public/* $OUTPUTDIR
cd $OUTPUTDIR
echo "tshepang.net" > CNAME
git add --all
git commit --message "build"
git push origin master
hg push
