#!/bin/bash -e

OUTPUTDIR='.output'
gutenberg build
rm --recursive $OUTPUTDIR/*
cp --recursive public/* $OUTPUTDIR
cd $OUTPUTDIR
git add --all
git commit --message "build"
git push origin master
hg push
