#!/bin/bash -e

OUTPUTDIR='.output'
zola build
rm --recursive $OUTPUTDIR/*
cp --recursive public/* $OUTPUTDIR
cd $OUTPUTDIR
git add --all
git commit --message "build"
git push origin main
cd -
git push
git push HEAD:refs/patches
